NAME="mongodb"

FCHECK="$PREFIX/bin/mongod"

BASE="mongodb-linux-$ARCH-static-$VERSION"
LOG="$LOG_PATH/$BASE.log"
rm -f $LOG &> /dev/null


function build(){
	cd $SRC_PATH/externals

	if [ ! -e $BASE ]; then
		extract_archive "$BASE.tgz"
	fi
	cd $BASE
}

function install(){
	echo " + Install ..."
	cp -R bin/* $PREFIX/bin/
	check_code $?

	echo " + Post install configurations ..."
	
	install_basic_source $NAME

	install_init "mongodb"
}
