NAME="celery"

LOG="$LOG_PATH/$NAME.log"
rm -f $LOG &> /dev/null

function build(){
	true
}

function easy_install_pylib(){
  echo "Easy install Python Library: $1 ..."
  $PREFIX/bin/easy_install -H None -f $PREFIX/share/pylibs/ $1 1>> $LOG 2>> $LOG
  check_code $? "Easy install failed ..."
}

function install(){
  install_basic_source $NAME
	install_python_daemon "$PREFIX/bin/celeryd"
	cd $PREFIX
	easy_install_pylib "celery"
}
