NAME="wkhtmltopdf"

FCHECK="$PREFIX/bin/wkhtmltopdf"

BASE="wkhtmltopdf-$VERSION-static-$ARCH"
LOG="$LOG_PATH/$BASE.log"
rm -f $LOG &> /dev/null


function build(){
	true
}

function install(){

	cd $PREFIX/bin
	tar xfj $SRC_PATH/externals/$BASE.tar.bz2
	echo $ARCH	
	if [ "$ARCH" == "i386" ]; then
		ln -s wkhtmltopdf-i386 wkhtmltopdf &> /dev/null
	elif [ "$ARCH" == "x86_64" ]; then
		ln -s wkhtmltopdf-amd64 wkhtmltopdf &> /dev/null
	fi	

	install_basic_source $NAME
}
