#!/bin/bash

if [ "$1" = "start" ]; then
	service rabbitmq-server start
	service mongodb start
	service amqp2mongodb start
	service nagios2amqp start
	service sla2mongodb start
	service amqp2perfstore start
	#service amqp2graphite start
	#service carbon-cache start
	#service graphite_webserver start
fi

if [ "$1" = "stop" ]; then
	#service graphite_webserver stop
	#service carbon-cache stop
	#service amqp2graphite stop
	service nagios2amqp stop
	service amqp2perfstore stop
	service sla2mongodb stop
	service amqp2mongodb stop
	service rabbitmq-server stop
	service mongodb stop
fi
