#!/usr/bin/env python

from caccount import caccount
from cstorage import cstorage
from cselector import cselector
from crecord import crecord
from csla import csla

namespaces = ['cache', 'inventory', 'history', 'sla', 'object']

## Create root account
account = caccount(user="root", group="root")

## Create storage
storage = cstorage(account, namespace='object')
for namespace in namespaces:
	storage.drop_namespace(namespace)

## Save account
storage.put(account)

## Save Selectors
selector = cselector(name="all-services", storage=storage, namespace="inventory")
selector.mfilter = {'source_type': 'service'}
selector.save()

selector = cselector(name="all-hosts", storage=storage, namespace="inventory")
selector.mfilter = {'source_type': 'host'}
selector.save()

## Save SLA
sla = csla(name="all-services", storage=storage, selector=selector)
sla.data['threshold_warn'] = 98
sla.data['threshold_crit'] = 95
sla.save()


