###################################
# Makefile for NEB2Socket
###################################

all: clean neb2socket.o

neb2socket.o:
	cd src && make

clean:
	cd src && make clean
	rm -f *.o
	#rm -f *~ *.*~

install:

