#!/bin/bash
#--------------------------------
# Copyright (c) 2011 "Capensis" [http://www.capensis.com]
#
# This file is part of Canopsis.
#
# Canopsis is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Canopsis is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Canopsis.  If not, see <http://www.gnu.org/licenses/>.
# ---------------------------------

function clean_cache () {
	echo " :: Clean cache"
	echo "    + Remove Remote Db"
	rm -Rf $REMOTE_DB_PATH
	echo "    + Remove old packages"
	for file in $PACKAGES_PATH/* ; do
		keep_it="False"
		while read line; do
			L_PNAME=$(echo "$line" | cut -d '|' -f1)
			tmp="${file%.[^.]*}"
			C_PNAME="${tmp##*/}"
			if [ "$C_PNAME" == "$L_PNAME" ]; then
				keep_it="True"
			fi
    	done < "$LOCAL_DB_PATH"
		if [ "$keep_it" == "False" ]; then
			rm -Rf $file
		fi
	done
	check_code $? "Failure during remove old database"
	echo "    + Update Pkgmgr info file"
	sed "/LAST_UPDATE/d" -i $VARLIB_PATH/info
	echo "    + Remove tmp.file"
	rm -Rf $TMP_FILE
	echo "    + Done"
	exit 1
}
