#!/bin/bash                                                                                             
#--------------------------------
# Copyright (c) 2011 "Capensis" [http://www.capensis.com]
#
# This file is part of Canopsis.
#
# Canopsis is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Canopsis is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Canopsis.  If not, see <http://www.gnu.org/licenses/>.
# ---------------------------------

function check_code () {
    if [ $1 -ne 0 ]; then
        echo -e "Error: Code: $1"
        echo -e "Output:\n$2"
		echo " => $PNAME installation failed"
        echo "[`date +'%T %x'`][ERR] $PNAME installation failed ($1)" >> $LOG_FILE
        echo "[`date +'%T %x'`][ERR] Output: ($2)" >> $LOG_FILE
        off_lock
        exit $1
    fi
}

function launch_cmd () {
	shift
    MYCMD=$@
    if [ "x$MYCMD" != "x" ]; then
        if [ "x`id -un`" == "x$HUSER" ]; then
            $MYCMD 2>&1 | tee -a $LOG_FILE ; test ${PIPESTATUS[0]} -eq 0
            EXCODE=$?
            check_code $EXCODE "Error in command '$MYCMD'..."
        else
            if [ `id -u` -eq 0 ]; then
                su - $HUSER -c ". .bash_profile && $MYCMD"
                EXCODE=$?
                check_code $EXCODE "Error in command '$MYCMD'..."
            else
                echo "Impossible to launch command with '`id -un`' ..."
                exit 1
            fi
        fi
    fi
}
