#!/bin/bash

function build_deps_tree(){
	init_tmp
	parse_deps $@
	clean_tree
}

function init_tmp(){
	rm -Rf $TMP_FILE
	touch $TMP_FILE
}

function clean_tree(){
	sed 's# #\n#g' $TMP_FILE | awk ' !x[$0]++'
}

function parse_deps(){
	D_TREE="$@ $D_TREE"
    for dep in $@; do
		local DBINFO=$(cat $REMOTE_DB_PATH | grep "^$dep|" | tail -n1)
        local L_DEPS=$(db_parse "deps" "$DBINFO")

        if [ -z "$L_DEPS" ]; then NB_DEPS=0;
        else NB_DEPS=$(echo $L_DEPS | sed 's# #\n#g' | wc -l); fi

        if [ $NB_DEPS -gt 0 ]; then
            parse_deps $L_DEPS
        else
			echo "$L_DEPS" "$D_TREE" > $TMP_FILE
        fi
    done
}
