#!/bin/bash
#--------------------------------
# Copyright (c) 2011 "Capensis" [http://www.capensis.com]
#
# This file is part of Canopsis.
#
# Canopsis is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Canopsis is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Canopsis.  If not, see <http://www.gnu.org/licenses/>.
# ---------------------------------

list_bin_files () {
	PPATH=$1
	cat $PPATH/files.lst | grep -v '^./etc/' | while read bin_line; do echo $bin_line; done
 }

list_conf_files () {
	PPATH=$1
	cat $PPATH/files.lst | grep '^./etc/' | while read conf_line; do echo $conf_line; done
}

extract_all () {
	PPATH=$1
	log_info "Create extract folder"
	trap 'error ${LINENO} "Try to mkdir .extract folder ($PPATH/.extract)"' ERR
	mkdir -p $PPATH/.extract
	log_info "Untar files.bz2 into extract folder"
	trap 'error ${LINENO} "Untar files.bz2 into extract ($PPATH/files.bz2 to $PPATH/.extract)"' ERR
	tar xf $PPATH/files.bz2 -C $PPATH/.extract
}

install_bin () {
	PPATH=$1
	list_bin_files $PPATH |
		while read t_line ; do
			dir_name=$(echo $t_line | sed -e 's_/[^/]*$__')
			mkdir -p $PREFIX/$dir_name
			mv $PPATH/.extract/$t_line $PREFIX/$t_line
		done
}

install_conf () {
	PPATH=$1
	list_conf_files $PPATH | 
		while read t_line ; do
			dir_name=$(echo $t_line | sed -e 's_/[^/]*$__')
			mkdir -p $PREFIX/$dir_name
			if [ ! -e $PREFIX/$t_line ]; then
				mv $PPATH/.extract/$t_line $PREFIX/$t_line
			else	
				old_md5=$(md5sum $PREFIX/$t_line | awk '{ print $1 }')
				new_md5=$(md5sum $PPATH/.extract/$t_line | awk '{ print $1 }')
				if [ "$old_md5" != "$new_md5" ]; then
					echo "      | New config file ($t_line) named *.new"
					mv $PPATH/.extract/$t_line $PREFIX/$t_line.new
				else
					mv $PPATH/.extract/$t_line $PREFIX/$t_line
				fi
			fi
		done 
}
