#!/bin/bash
#--------------------------------
# Copyright (c) 2011 "Capensis" [http://www.capensis.com]
#
# This file is part of Canopsis.
#
# Canopsis is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Canopsis is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Canopsis.  If not, see <http://www.gnu.org/licenses/>.
# ---------------------------------

# Install all files except conf files
function install_bin () {
	PPATH=$1
	tar xf $PPATH/files.tgz --exclude='^./etc*'
}

# Install conf files
function install_conf () {
	PPATH=$1
	mkdir -p $PPATH/.extract
	list_conf_files $PPATH | 
		while read line ; do
			tar xf $PPATH/files.tgz -C $PPATH/.extract --wildcards './etc*'
			old_md5=$(md5sum $PREFIX/$line)
			new_md5=$(md5sum $PPATH/.extract/$line)
			if [ "$old_md5" != "$new_md5" ]; then
				echo "      | New config file ($line) named *.new"
				mv $PPATH/.extract/$line $PREFIX/$line.new
			fi
			#echo "  _old-md5: $old_md5"
			#echo "  _new-md5: $new_md5"
			#tar xf $PPATH/files.tgz --wildcards './etc*'
		done 
}
