#!/bin/bash
#--------------------------------
# Copyright (c) 2011 "Capensis" [http://www.capensis.com]
#
# This file is part of Canopsis.
#
# Canopsis is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Canopsis is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Canopsis.  If not, see <http://www.gnu.org/licenses/>.
# ---------------------------------

# List binaries files
function list_bin_files () {
	PPATH=$1
	cat $PPATH/files.lst | grep -v '^./etc/' | while read bin_line; do echo $bin_line; done
}

# List conf files
function list_conf_files () {
	PPATH=$1
	cat $PPATH/files.lst | grep '^./etc/' | while read conf_line; do echo $conf_line; done
}
