#!/bin/bash
#--------------------------------
# Copyright (c) 2011 "Capensis" [http://www.capensis.com]
#
# This file is part of Canopsis.
#
# Canopsis is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Canopsis is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Canopsis.  If not, see <http://www.gnu.org/licenses/>.
# ---------------------------------

#on_die () {
#	log_info "Exit pending..."
#	exit_pending=true
#	if ! [ -e "$LOCK_FILE" ]; then 
#		echo
#		echo "Abort."
#		exit 1
#	else
#		echo "Wait..."
#	fi
#}

on_lock () {
	log_info "Create lock file"
	stty intr undef
	trap 'error ${LINENO} "Try to create lock file ($LOCK_FILE)"' ERR
	touch $LOCK_FILE
}

off_lock () {
	stty intr "^C"
	log_info "Remove lock file"
	trap 'error ${LINENO} "Try to remove lock file ($LOCK_FILE)"' ERR
	rm -Rf $LOCK_FILE
	#check_lock
}

check_lock () {
	if [[ ! -e "$LOCK_FILE" ]]; then
		if $exit_pending ; then
			echo
			echo "Abort."
			exit 1
		fi
	fi
}
