#!/bin/bash
#--------------------------------
# Copyright (c) 2011 "Capensis" [http://www.capensis.com]
#
# This file is part of Canopsis.
#
# Canopsis is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Canopsis is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Canopsis.  If not, see <http://www.gnu.org/licenses/>.
# ---------------------------------

function show_help () {
	echo
	echo " :: Usage : pkgmgr [ACTION] [OPTIONS] <package>"
	echo
	echo " :: Actions"
	echo "   install [OPT] [PKG]            ->  Install package(s)"
	echo "   install-local [OPT] [PKGPATH]  ->  Install local package(s)"
	echo "   reinstall [PKG]                ->  Reinstall package(s)"
	echo "   reinstall-local [PKGPATH]      ->  Reinstall local package(s)"
	echo "   upgrade [PKG]                  ->  Upgrade package(s)"
	echo "   remove [OPT] [PKG]             ->  Remove package(s)"
	echo "   update                         ->  Update local database"
	echo "   list                           ->  List packages"
	echo "   clean                          ->  Clean cache"
	echo "   help                           ->  Print this help"
	echo
	echo " :: Options"
	echo "   --force-yes                    -> Force yes answer"
	echo
	echo " :: Examples"
	echo "   pkgmgr install python erlang"
	echo "   pkgmgr remove --force-yes ccli"
	echo "   pkgmgr reinstall --force-yes pyperfstore"
	echo "   pkgmgr install-local /root/mypkg.tar mypkg2.tar"
	echo "   pkgmgr upgrade webcore"
	echo 
	echo " :: Informations"
	echo "    - Remove feature have no dependencies tracking, be careful"
	echo "    - (*) after package name mean that your repositorie doesn't have it"
	echo
	echo "   More informations on http://canopsis.com/"
	exit 1
}
